### ISSUE TITLE
Column storage implementation using std::tuple

### ISSUE THREAD

**Issue by skyrpex** [alecthomas/entityx#111]
I wonder if there's any drawback using std::tuple for keeping memory aligned entities. Currently, the memory is managed manually in Column Storage class.

Something like this:

```c++
std::vector<std::tuple<Cs...>> components;
```

**Comment by alecthomas** [comment]
Tuple will default construct all its members.

**Comment by skyrpex** [comment]
first, sorry to bother you  :panda_face: what's wrong with that? as far as I know, it could only get a bit slower when creating or resizing the container

**Comment by alecthomas** [comment]
Right, but what's the upside?

**Comment by skyrpex** [comment]
Being able to remove get_component_index, get_component_size, is_valid_component, get_component_offset, get_component_size_sum and substitute ColumnStorage's current implementation (which has lots of low level code) for a fairly simple one based on vectors of tuples.

**Comment by alecthomas** [comment]
That implementation exists *because* `std::tuple` is too inefficient for this use case. That, and `std::get<C>` only exists in >= C++14.

Here is the actual overhead comparison (AFAICT; it is hard to find details on how `std::tuple` operates):

Operation | Current implementation overhead | `std::tuple` overhead
--------------|----------------------------------------------|-----------------------------
Expand | malloc(chunk_size) | Call constructor on new objects, call copy (or move) constructor on existing objects that have to be moved, then destructors
`assign<C>` | (call destructor if assigned), placement new | call constructor of new component, call destructor of existing, call assignment operator, call destructor
`remove<C>` | (call destructor if assigned) | call destructor

The other reason for the current implementation is that each component is stored in a column, in order to increase cache coherency. Storing in a tuple means that you will basically get no cache coherency whatsoever.

Does that answer your original question about the drawbacks?

That said, you could implement a `ColumnStorage` implementation using `std::tuple` if you desired.

**Comment by skyrpex** [comment]
Thanks for the feedback. I'm just trying to get documented, not trying to change your mind.

```The other reason for the current implementation is that each component is stored in a column, in order to increase cache coherency. Storing in a tuple means that you will basically get no cache coherency whatsoever.```

I thought that having a tuple meant having each component to be stored in a column. I guess that I understood exactly the oppossite! I'll look your implementation a bit better.
