### ISSUE TITLE
Events about adding/removing component

### ISSUE THREAD

**Issue by AIGRIND-LLC** [alecthomas/entityx#168]
Hello,
When we assign or remove some component the` ComponentAddedEvent`/`ComponentRemovedEvent` events will be emitted. There is a difference in interpretation of these events.
In `ComponentAddedEvent<C>` handler the call `entity.has_component<C>()` returns `true` and this fact let us suppose that component has been already assigned to the entity.
But in `ComponentRemovedEvent<C>` handler the call `entity.has_component<C>()` returns also `true`, but why? In this case we can not rely on `has_component()` method.

**Comment by alecthomas** [comment]
`has_component<>` is [accurate](https://github.com/alecthomas/entityx/blob/master/entityx/Entity.h#L656). `ComponentRemovedEvent` is called before the component is actually removed (despite the name).

**Comment by AIGRIND-LLC** [comment]
Thus this kind of code will not work. Am I right?

```cpp
void NameSystem::receive(const entityx::ComponentAddedEvent<NameComponent>& event)
{
	UpdateEntityName(event.entity);
}

void NameSystem::receive(const entityx::ComponentRemovedEvent<NameComponent>& event)
{
	UpdateEntityName(event.entity);
}

void NameSystem::UpdateEntityName(const entityx::Entity& entity)
{
	if (entity.has_component<NameComponent>())
	{
		ShowNameForEntity(entity);
	}
	else
	{
		HideNameForEntity(entity);
	}
}
```

**Comment by Naburimannu** [comment]
Why would you want that kind of code to work? Putting the ShowName/HideName calls in the two receive() calls seems much saner, rather than adding an additional intermediary function that *throws out information*. You know whether the name is added or removed, but you're ignoring that fact in your function call, then making an additional function call inside UpdateEntityName to try to regain that knowledge.

**Comment by alecthomas** [comment]
@AIGRIND-LLC correct, that code will always execute `ShowNameForEntity(entity)`.

**Comment by AIGRIND-LLC** [comment]
Ok, thanks!

**Comment by zackthehuman** [comment]
It makes sense to me that the event for removal would happen before the component is actually removed, otherwise you would have no way of accessing the component in your handler because it would already be gone.

Perhaps the event should have been called `ComponentWillBeRemovedEvent` or some such name. In any case, the way it works seems good IMO.
