### ISSUE TITLE
LNK2019 / LNK2001 / LNK1120 Error [VS2017]

### ISSUE THREAD

**Issue by Raigiku** [alecthomas/entityx#206]
After installing entityx and adding the SFML sample file found here: https://github.com/alecthomas/entityx/blob/master/examples/example.cc
I get this error:
![image](https://user-images.githubusercontent.com/31873735/37250428-5b50d35c-24ca-11e8-87a0-fae39dd0bc5e.png)
When I double click it, it leads me to the Entity.h file and to line 464:
![image](https://user-images.githubusercontent.com/31873735/37250431-71933c22-24ca-11e8-9619-7f102b1b068e.png)

**Comment by alecthomas** [comment]
I don't have VS, and an internal compiler error isn't something I can do a lot about...

**Comment by alecthomas** [comment]
Have you installed all of the latest SV updates, including spot patches?

**Comment by Raigiku** [comment]
Ok that fixed it but now I have these problems:
![image](https://user-images.githubusercontent.com/31873735/37250930-f850394a-24d4-11e8-86d9-d7cb87a25f9a.png)
I think it has to do with linking libs but I don't really know how should I do it with the ones from entiyx they aren't .lib like in SFML. I have libentityx.dll.a / entityx.pc / libentityx.dll

**Comment by zlixine** [comment]
It looks like you don't have EntityX .cpp files (all those functions are defined in them).

**Comment by Raigiku** [comment]
Well, when I finished installing it with CMake and make I get 3 folders and no .cpp files: 
**bin**
--libentityx.dll
**include**
--entityx
![image](https://user-images.githubusercontent.com/31873735/37263797-c5766c44-2577-11e8-804c-206f12a3a59a.png)
**lib**
--pkgconfig
----entityx.pc
--libentityx.dll.a
I've only added the include folder to the **Additional Include Directories** of my Visual Studio project. I've also added the lib folder to the **Additional Library Directories** and the libentityx.dll to the path where the .exe is suppose to be generated. The folder (.zip) that I downloaded is the one from the github repository.

**Comment by gale93** [comment]
If you want the .lib files, build with cmake ENTITYX_BUILD_SHARED disabled
Then you go build the entityx.sln and generating the lib ( You found them in Release and Debug folder )

So now you go back in your project and:

[All Configuration] **C/C++ / Additional Include Directories** entityx folder where .h files are.
[All Configuration] **Linker / Additional Library Directories** create a folder "lib" and put the 2 libs u got from generating ( entityx.lib, entityx-d.lib ) and set that path

[DEBUG] **Linker / input** add entityx-d.lib 
[RELEASE] **Linker / input** add entityx.lib 

And there you go.

I can attach mine here but are compiled with /MT and /MTd because i need the project work with RakNet files, so if you want to use them you have to change these flag under **C/C++ / Code generation / runetime lib**. [lib.zip](https://github.com/alecthomas/entityx/files/1807253/lib.zip)

P.s.: No need to define M_PI, just `#define _USE_MATH_DEFINES` before include cmath.

**Comment by alecthomas** [comment]
Thanks @gale93 .
