### ISSUE TITLE
Inherited Component Polymorphism?

### ISSUE THREAD

**Issue by jasonmeverett** [alecthomas/entityx#241]
Let's say I have a base component type:

```
struct Moveable  : public Component<Moveable>
{
    virtual void Update() = 0;
}
```

And I'd like to customize the component as follows:
```
struct MyMoveable : public Moveable
{
    void Update() override;
}
```

Then, I'd like to be able to get a list of all `Moveable` types as:

```
ComponentHandle<Moveable> MoveableComponent;
for(entityx::Entity entity : es.entities_with_components(MoveableComponent))
{
    // In here, I want access to MyMoveable.
}
```

**Comment by alecthomas** [comment]
Hi there. This is a fairly common misconception of how ECS works (see #171 and #42 for example). You do not want to use inheritance with ECS components at all. Instead of thinking of each _component_ as a distinct class hierarchy, think of each _entity_ as the composition of all the features you want that entity to have. So in your example you might have an `Updateable` and a `Moveable` component and you would do the following:


```c++
ComponentHandle<Moveable> MoveableComponent;
ComponentHandle<Updateable> UpdateableComponent;
for(entityx::Entity entity : es.entities_with_components(MoveableComponent, UpdateableComponent))
{
}

```

**Comment by jasonmeverett** [comment]
This is great insight. Thanks for the help!
