### ISSUE TITLE
More elegant iteration

### ISSUE THREAD

**Issue by alecthomas** [alecthomas/entityx#62]
I've noticed this pattern occurs very frequently, where the entity is thrown away when iterating over components. It's also kind of redundant having to pre-declare the component handles:

```c++
  void update(EntityManager &entities, EventManager &events, TimeDelta dt) override {
    Notification::Handle notification;
    for (auto _ : entities.entities_with_components(notification)) {
      notification->components_added.reset();
      notification->components_removed.reset();
    }
  }
```

With `std::tuple` this could be simplified to:

```c++
  void update(EntityManager &entities, EventManager &events, TimeDelta dt) override {
    for (auto c : entities.with_components<Notification>()) {
      std::get<0>(c)->components_added.reset();
      std::get<0>(c)->components_added.reset();
    }
  }
```

Better? Worse? Unsure.

**Comment by andjscott** [comment]
How about a tie?
        
    ex::Entity entity;
    Body::Handle body;
    for (std::tie(entity, body) : es.entities_with_components<Body>()) {
        cout << "entity[" << entity.id() << "] at " << body->position.x << ", " << body->position.y << endl;
    }

**Comment by sansumbrella** [comment]
A functional style iteration pattern would be pretty excellent.

Maybe something like the following, so we don't need to declare handles or references up front. It would be event more amazing if you could deduce the parameter types from the function parameter to each, but that might be asking too much of the language at this point.

```c++
// color things based on a collision
entities.with_components<Physics, Style>().each([] (Physics &p, Location &l, Style &s) {
  if (p.collided) {
   style.color = "red";
  }
});

// synchronize world location with simulation location.
entities.with_components<Physics, Location>().each([] (Physics &p, Location &l) {
  l.position = p.position;
});
```

```c++
// is the compile-time type deduction possible here?
entities.for_components([] (Physics &p, Location &l) {
…
});
```

The first approach seems pretty feasible to me:
`with_components<Types...>` can return a traversal/iterator type based on the types provided. The `each` method of that type loops over the relevant entities and calls the provided function with their references at each step.

Would be curious to see how compilers treated that, though. Hopefully the function body would end up being inlined instead of called repeatedly.

**Comment by alecthomas** [comment]
That is a great idea. Off-hand I don't think it would be difficult to implement either.

**Comment by Gronis** [comment]
Are you sure this method is inlined? I have tried your implemented method [here](http://gcc.godbolt.org/#%7B%22version%22:3,%22filterAsm%22%3a%7B%22labels%22%3atrue,%22directives%22%3atrue,%22commentOnly%22%3atrue,%22colouriseAsm%22%3atrue%7D,%22compilers%22%3a%5B%7B%22source%22%3a%22#include%20%3Ciostream%3E%5Cn#include%20%3Cfunctional%3E%5Cn%5Cnusing%20namespace%20std;%5Cn%5Cnint%20h;%5Cnvoid%20test%28const%20std%3a%3afunction%3Cvoid%28%29%3E%20fn%29%7B%5Cn%20%20%20%20fn%28%29;%5Cn%7D%5Cnint%20main%28%29%20%7B%5Cn%5Cn%20%20%20%20test%28%5B%5D%20%28%29%20%7B%20h=3;%7D%29;%5Cn%20%20%20%20return%200;%5Cn%7D%5Cn%22,%22compiler%22%3a%22/usr/bin/g++-4.8%22,%22options%22%3a%22-O4%20-std=c++11%22%7D%5D%7D), and it is not inlined. According to [this](http://stackoverflow.com/questions/21407691/c11-inline-lambda-functions-without-template) SO question, this cannot be done without templating the function. Am I missing something or might this be the case?

**Comment by alecthomas** [comment]
It doesn't look like it can :(

**Comment by Gronis** [comment]
That's a shame :/ would be awesome to write the loop like that and get the same performance as before (or even better since we do not always unpack Entity) Perhaps this is as good as it gets.

**Comment by Gronis** [comment]
Is the reason of using entities.with_components(components...) over entities.with_components<Components...>() for improved performance by unpacking the components each loop iteration instead of when accessed with entity.component<Component>()? Or is it just for a more elegant solution? 

In case this is done for performance. You could implement an UnpackedEntity<Components...> that is a wrapper of std::tuple<Components...>. Then create a wrapper function UnpackedEntity<Components...>::component<Component>() which calls std::get<number> on the appropriate component. 

This way would still look like using an ordinary entity, (more elegan then std::get according to me) but basically is the same thing as your original proposal. What do you think?

**Comment by Gronis** [comment]
Providing an each function with a signature like this
```
entities.for_components([] (Comp1& c1, Comp2& c2...) {});
 ```
instead of this
```
entities.for_components<Comp1, Comp2>([] (Comp1& c1, Comp2& c2...) {}); 
```
is achievable by using the whole lambda as a template parameter like this
```
template<typename Lambda>
EntityManager::for_components(Lambda lambda); 
```
and then extract the lambda parameters using this guys method: http://stackoverflow.com/questions/7943525/is-it-possible-to-figure-out-the-parameter-type-and-return-type-of-a-lambda

I have tried this out and it works. It is also more possible that the lambda will inlined (not yet confirmed) since the whole expression is part of the template parameter (see http://stackoverflow.com/questions/21407691/c11-inline-lambda-functions-without-template)

**Comment by alecthomas** [comment]
Pretty interesting, though the template mechanics for unpacking components means that I would have to replicate each specialisation for each callsite (EntityManager::each and View*::each), making a total of about 6-8 templates specialisations.

I'm not sure that the syntactical improvement alone is worth it, though the inlining may well be...

**Comment by Gronis** [comment]
Have you tried to write some performance tests with the new lambda iteration function? If it is remarably slower, this change might be worth it.
