### ISSUE TITLE
Alternate component pooling policies

### ISSUE THREAD

**Issue by wivlaro** [alecthomas/entityx#86]
At the moment, for any new entity, the only pool implementation is allocated in contiguous blocks of 8192 entities. It would be good to be able to have some different strategies for sparsely-populated/large components, or where we know the number of entities in a system is never going to reach 8192.

**Comment by alecthomas** [comment]
There is a discussion issue on this in #68. Please feel free to discuss over there.

The [experimental/compile_time](https://github.com/alecthomas/entityx/tree/experimental/compile_time) branch actually supports pluggable storage engines that achieve this. That said, other aspects of the branch cause issues:

- Does not work in MSVC++ due to compiler limitations.
- Generates large error messages due to template expansion.
